### ISSUE TITLE
React Version not working with react-router-dom 6

### ISSUE THREAD

**Issue by seschi98** [Webtrekk/Webtrekk-Smart-Pixel#8]
When using `@webtrekk-smart-pixel/react` with `react-router-dom` 6.3.0 the following error occurs:

```
Uncaught TypeError: reactRouterDom.withRouter is not a function
  at smart-pixel-react.umd.js:664:1
  at smart-pixel-react.umd.js:2:1
  at ./node_modules/@webtrekk-smart-pixel/react/dist/smart-pixel-react.umd.js (smart-pixel-react.umd.js:5:1)
  at options.factory (react refresh:6:1)
  at __webpack_require__ (bootstrap:24:1)
  at fn (hot module replacement:62:1)
  at ./node_modules/@webtrekk-smart-pixel/react/index.js (index.js:4:1)
  at options.factory (react refresh:6:1)
  at __webpack_require__ (bootstrap:24:1)
  at fn (hot module replacement:62:1)
```

Minimal reprodution: https://codesandbox.io/s/musing-sky-q28uoz

This is because in newer versions of react-router-dom the `withRouter` hook is no longer available. The hook is used in [WebtrekkAutoTracking.js](https://github.com/Webtrekk/Webtrekk-Smart-Pixel/blob/8b2f3b1dba82eb9e04369f8469fc67de37063fae/packages/react/vanilla/src/components/WebtrekkAutoTracking.js) to access the current navigation type in the `componentDidUpdate` lifecycle method:
https://github.com/Webtrekk/Webtrekk-Smart-Pixel/blob/8b2f3b1dba82eb9e04369f8469fc67de37063fae/packages/react/vanilla/src/components/WebtrekkAutoTracking.js#L34-L48

In `react-router-dom@v6` this information can be accessed using the [`useNavigationType`](https://reactrouter.com/docs/en/v6/hooks/use-navigation-type) hook.

**Comment by StephanGuenther** [comment]
Fixed with v1.2.3
